# use NodeJS as language
language: node_js

# node version to use on builds (node vs iojs)
node_js:
  - node

# enable caching of directories.
cache:
  directories:
    - node_modules

# install missing libraries for nodegit
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

# build script
script: npm run build

# pre deployment scripts.
before_deploy:
  npm run deployOpenPullRequests

## deployment stage.
deploy:
  # deploys to prod
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  project: $FIREBASE_PROJECT_ID
  on:
    branch: master

  # deploys to dev
  provider: firebase
  skip_cleanup: true
  token: $FIREBASE_TOKEN
  project: $FIREBASE_DEV_PROJECT_ID
  on:
    branch: develop
